ALTER TABLE bucket_quotas
    ADD COLUMN IF NOT EXISTS current_bytes BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS current_objects BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS recalculated_at TIMESTAMPTZ;

ALTER TABLE user_quotas
    ADD COLUMN IF NOT EXISTS current_bytes BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS recalculated_at TIMESTAMPTZ;
